### ISSUE TITLE
Example App not running on XCode 6.1

### ISSUE THREAD

**Issue by abdul-rehman** [mdznr/MTZRadialMenu#3]
Getting this error while running example on XCode 6.1. Please can you assist me ?

ld: file not found: /Users/abdulrehman/Library/Developer/Xcode/DerivedData/Radial_Menu-dptkkvkltshykgdjiwgjqkhvzjkw/Build/Products/Debug-iphonesimulator/Example App.app/Example App
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fbara** [comment]
Same error on Xcode 6.2 beta.
