### ISSUE TITLE
Swift 3 integration:- No such module 'RadialMenu'

### ISSUE THREAD

**Issue by pkc456** [mdznr/MTZRadialMenu#7]
I have added below files on my swift 3project:-

- RadialMenu

- MTZButton

- MTZRadialMenu

- MTZRadialMenuItem_Private

- MTZRadialMenuItem

When I tried to create MTZRadialMenu as:-     `let cameraRadialMenu :  MTZRadialMenu?`, then I import RadialMenu as:- `import RadialMenu`, But it gives me below error
No such module 'RadialMenu'

How to integrate this library in swift 3?

![screen shot 2017-05-16 at 12 57 31 pm](https://cloud.githubusercontent.com/assets/1394476/26094382/6f878916-3a37-11e7-9734-0ee9f247619c.png)

**Comment by mdznr** [comment]
If you're building from source directly, no need to "import RadialMenu".
